const requests = {
  DECENTRO_IN_STAGING_BASE_URL: "https://in.staging.decentro.tech",
  DECENTRO_IN_QA_BASE_URL: "https://in.qa.decentro.tech",
  DECENTRO_WORKFLOW_BASE_URL_PROD: "https://workflow.decentro.tech/webhook",
  DECENTRO_WORKFLOW_BASE_URL_STAGING:
    "https://staging.workflow.decentro.tech/webhook",
  WORKFLOW_SIGNUP_ONBOARDING: "/india_signup/signup",
  DECENTRO_DC_MODE_LIST: "/dc_signup/mode_list",
  DECENTRO_DC_STAGE_LIST: "/dc_signup/stage_list",
  DECENTRO_DC_CITY_LIST: "/dc_signup/city_list",
  DECENTRO_DC_SIGNUP: "/dc_signup/signup",
  SIGNUP: "/signup/",
  YC_APPLICATION_LINK: "https://form.typeform.com/to/woHCbZEw",
  BUG_REPORT_FORM: "/report-bug/report",
  PARTNER_SIGNUP_INHOUSE: "/partner_sign_up",
  BUG_REPORT: "/bug_report_more",
  PARTNERS_SIGNUP: "https://decentro.typeform.com/to/u9QsvYUy",
  SIGNUP_DEBT_COLLECTION: "/dc/signup/",
  MODE_LIST: "/signup/mode_list",
  PRODUCT_LIST: "/signup/product_list",
  STAGE_LIST: "/sign_up_onboarding/stage_list",
  CITY_LIST: "/signup/city_list",
  SELF_CITY_LIST: "/sign_up_onboarding/city_list",
  NEWSLETTER_SUBSCRIBE:
    "https://api.moosend.com/v3/subscribers/4dee5aab-9980-48a6-8d38-5d64da1b1f7e/subscribe.json?apikey=4ea174c1-f494-431f-9128-21c183bc4b88",
  FINTECH_FELLOWSHIP_SIGNUP: "https://decentro.typeform.com/to/pWX0BTZa",
  SIGNUP_ONBOARDING: "/sign_up_onboarding",
  UNIQUENESS_CHECK: "/sign_up_onboarding/uniqueness_check",
  NEOWISE_SIGNUP: "/signup",
  NEOWISE_CITY_LIST: "/signup/city_list",
  NEOWISE_STAGE_LIST: "/signup/stage_list",
  NEOWISE_MODE_LIST: "/signup/mode_list",
  STRAPI_STAGING_BASE_URL: "https://staging.decentro.tech/strapi/",
  STRAPI_STAGING_API_BASE_URL: "https://staging.decentro.tech/strapi/api",
  STRAPI_STAGING_IP_BASE_URL: "https://strapi.decentro.tech",
  STRAPI_STAGING_API_IP_BASE_URL: "https://strapi.decentro.tech/api",
  STRAPI_DECENTRO_FAQS_MASTER_LINKS: "/decentro-faq-master-links",
  STRAPI_DECENTRO_FAQS_MASTER_CARDS: "/decentro-faq-master-cards",
  STRAPI_DECENTRO_FAQS_SUBLINKS: "/decentro-faq-sublinks",
  STRAPI_DECENTRO_FAQS: "/decentro-faq-mains",
  STRAPI_DECENTRO_FAQ_NAV_LINKS: "/decentro-faq-navigations",
  STRAPI_DECENTRO_SECTION_FAQS: "/decentro-section-faqs",
  STRAPI_DECENTRO_META_TAGS: "/decentro-faq-meta-tags",
  STRAPI_DECENTRO_FAQS_CTA: "/decentro-faq-ctas",
  STRAPI_DECENTRO_FAQS_TABLEDATA: "/table-datas",
  STRAPI_DECENTRO_HALL_OF_FAME: "/hall-of-fames",
  STRAPI_RESOURCES_PAGE: "/resource-pages",
  STRAPI_POPULATE_ALL_QUERY: "?populate=*",
  STRAPI_RP_POPULATE_ALL_QUERY:
    "?populate[RPBanner][populate]=*&populate[TableOfContents][populate]=*&populate[IntroductorySection][populate]=*&populate[RPInlineImageAndParagraph][populate]=*&populate[RPKeyFeatures][populate][RPKeyFeatureUnitBlock][populate]=*&populate[RPKeyFeatures][populate][KeyFeaturesBlocksRow2][populate]=*&populate[WhyDecentroSection][populate]=*&populate[RecommendedPages][populate]=*&populate[NeedSection][populate]=*&populate[TypesSection][populate][ImageTitleDescColumnMapUnit][populate]=*&populate[MethodologySection][populate]=*&populate[CTABannerStart][populate]=*&populate[CTABannerMiddle][populate]=*&populate[CTABannerEnd][populate]=*",
  ASSETS_BASE_URL_S3:
    "https://decentro-website-v2-assets.s3.ap-south-1.amazonaws.com",
  DOC_VA:
    "https://docs.decentro.tech/reference/virtual_accounts_api-create-a-virtual-account",
  DOC_UPI_COLLECTIONS: "https://docs.decentro.tech/docs/payments-collections",
  DOC_UI_STREAM:
    "https://docs.decentro.tech/docs/kyc-and-onboarding-workflows-uistreams",
  DOC_RECUR_PAYMENTS: "https://docs.decentro.tech/docs/payments-mandates",
  DOC_PAYOUTS: "https://docs.decentro.tech/docs/payments-direct-payouts",
  DOC_LEDGERS: "https://docs.decentro.tech/docs/ledgers",
  DOC_KYC_ONBOARDING: "https://docs.decentro.tech/docs/kyc-overview-and-guide",
  DOC_LENDING: "https://docs.decentro.tech/docs/lending-overview-and-guide",
  DOC_BYTES:
    "https://docs.decentro.tech/docs/financial_services-overview-and-guide",
  DOC_HYPERSTREAMS: "https://docs.decentro.tech/docs/kyc-hyperstreams",
  ISD_SIGNUP: "/isd_signup/signup",
  ISD_MODE_LIST: "/isd_signup/mode_list",
  ISD_STAGE_LIST: "/isd_signup/stage_list",
  ISD_PRODUCT_LIST: "/isd_signup/product_list",
  ISD_COUNTRY_CODE_LIST: "/isd_signup/isd_country_list",
};

export default requests;
