const urls = {
  ROOT_URL: "https://decentro.tech/global/",
  BASE_URL: "https://decentro.tech",
  VIRTUAL_ACCOUNTS: "/global/products/virtual-accounts",
  PAYMENT_COLLECTION: "/global/products/global-payment-collection",
  MULTI_CURRENCY_ACCOUNTS: "/global/products/multi-currency-accounts",
  RECURRING_PAYMENTS: "/global/products/recurring-payments",
  INSTANT_PAYOUTS: "/global/products/instant-payouts",
  KYC_AND_ONBOARDING: "/global/products/kyc-onboarding/",
  LEDGERS: "/global/products/ledgers/",
  LENDING: "/global/products/lending/",
  FINANCIAL_SERVICES: "/global/products/financial-services",
  HYPERSTREAMS: "/global/products/hyperstreams",
  SCAN_AND_EXTRACT: "/global/products/scan-and-extract",
  AADHAAR_XML: "/global/products/aadhaar-xml",
  RESOURCES: "/global/resources",
  RESOURCES_FAST: "/global/resources/fast-transfer/",
  RESOURCES_PAYNOW: "/global/resources/paynow",
  RESOURCES_CKYC_APIS: "/global/resources/ckyc-apis",
  RESOURCES_GST_APIS: "/global/resources/goods-and-services-tax-gst-api/",
  RESOURCES_UPI_APIS: "/global/resources/upi-apis",
  RESOURCES_CREDIT_BUREAU_APIS: "/global/resources/credit-bureau-api",
  RESOURCES_UPI_AUTOPAY_APIS: "/global/resources/upi-autopay-apis",
  RESOURCES_ENACH_APIS: "/global/resources/enach-apis",
  RESOURCES_DIGILOCKER_APIS: "/global/resources/digilocker-apis",
  RESOURCES_UPIID_VERIFICATION: "/global/resources/upi-verification",
  RESOURCES_BANK_ACCOUNT_VALIDATION:
    "/global/resources/bank-account-validation-api",
  RESOURCES_DIGITAL_LENDING: "/global/resources/digital-lending-solution",
  RESOURCES_DEBT_COLLECTION: "/global/resources/debt-collection-software",
  RESOURCES_BULK_PAYOUTS: "/global/resources/bulk-payouts",
  SIGNUP_DEBT_COLLECTION: "/dc/signup/",
  ABOUT: "/global/about",
  PRESS: "/global/press-buzz",
  CAREER: "/global/careers",
  CUSTOMER_STORIES: "/global/customer-stories",
  COMPLIANCE: "/global/compliance",
  GRIEVANCE: "/global/grievance",
  AGREEMENT: "/global/agreement",
  BLOG: "/blog",
  TERMS: "/global/terms",
  PRIVACY: "/global/privacy",
  MSA: "/global/agreement",
  HELP: "/global/help",
  HELP_FAQS: "/global/help/faqs",
};

export default urls;
