const utmtags = {
  HOMEPAGE_SIGNUP_FIRST_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=homepage_signup_button",
  HOMEPAGE_CONNECT_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=homepage_signup_submit",
  KYC_GET_STARTED_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=KYC_module_top_signup_button",
  KYC_SIGNUP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=KYC_module_bottom_signup_button",
  ACCOUNTS_GET_STARTED_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=accounts_top_signup_button",
  ACCOUNTS_JOIN_REVOLUTION_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=accounts_join_the_revolution_button",
  ACCOUNTS_SIGNUP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=accounts_bottom_signup_button",
  SAVINGS_ACCOUNTS_GET_STARTED_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=savings_accounts_top_signup_button",
  SAVINGS_ACCOUNTS_JOIN_REVOLUTION_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=savings_accounts_join_the_revolution_button",
  VIRTUAL_ACCOUNTS_GET_STARTED_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=virtual_accounts_signup_button",
  VIRTUAL_ACCOUNTS_JOIN_REVOLUTION_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=virtual_accounts_join_the_revolution_button",
  BUSINESS_ACCOUNTS_GET_STARTED_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=business_accounts_signup_button",
  BUSINESS_ACCOUNTS_JOIN_REVOLUTION_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=business_accounts_join_the_revolution_button",
  PAYMENTS_GET_STARTED_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=payments_signup_button",
  PAYMENTS_SIGNUP_IN_SECONDS_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=payments_signup_in_seconds_button",
  CARDS_GET_STARTED_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=cards_signup_button",
  CARDS_SIGNUP_IN_SECONDS_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=cards_signup_in_seconds_button",
  LENDING_GET_STARTED_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=lending_signup_button",
  LENDING_SIGNUP_FOR_FREE_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=lending_signup_for_free_button",
  LENDING_JOIN_REVOLUTION_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=lending_join_the_revolution_button",
  NEOBANKS_GET_STARTED_TOP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=neobanks_signup_button",
  NEOBANKS_GET_STARTED_MIDDLE_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=neobanks_signup_middle_button",
  NEOBANKS_SIGNUP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=neobanks_signup_bottom_button",
  MARKETPLACES_GET_STARTED_TOP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=marketplaces_signup_top_button",
  MARKETPLACES_GET_STARTED_MIDDLE_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=marketplaces_signup_middle_button",
  MARKETPLACES_SIGNUP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=marketplaces_signup_bottom_button",
  ERPS_GET_STARTED_TOP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=ERP_signup_top_button",
  ERPS_GET_STARTED_MIDDLE_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=ERP_signup_middle_button",
  ERPS_SIGNUP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=ERP_signup_bottom_button",
  GIG_PLATFORMS_GET_STARTED_TOP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=GIG_platforms_signup_top_button",
  GIG_PLATFORMS_GET_STARTED_MIDDLE_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=GIG_platforms_signup_middle_button",
  GIG_PLATFORMS_SIGNUP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=GIG_platforms_signup_bottom_button",
  PSP_GET_STARTED_TOP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=payment_services_signup_top_button",
  PSP_GET_STARTED_MIDDLE_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=payment_services_signup_middle_button",
  PSP_SIGNUP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=payment_services_signup_bottom_button",
  WEALTH_PERSONAL_FINANCE_GET_STARTED_TOP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=wealth_signup_top_button",
  WEALTH_PERSONAL_FINANCE_GET_STARTED_MIDDLE_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=wealth_signup_middle_button",
  WEALTH_PERSONAL_FINANCE_SIGNUP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=wealth_signup_bottom_button",
  NBFC_GET_STARTED_TOP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=NBFC_signup_top_button",
  NBFC_GET_STARTED_MIDDLE_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=NBFC_signup_middle_button",
  NBFC_SIGNUP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=NBFC_signup_bottom_button",
  CRYPTO_GET_STARTED_TOP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=Crypto_signup_top_button",
  CRYPTO_SIGNUP_FOR_FREE_TOP_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=Crypto_signup_for_free_top_button",
  CRYPTO_SIGNUP_FOR_FREE_BOTTOM_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=Crypto_signup_for_free_bottom_button",
  ABOUTUS_CONNECT_WITH_US_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=About_us_connect_with_us_button",
  PARTNERS_LETS_CONNECT_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=Partners_let's_connect_button",
  CUSTOMER_STORIES_GET_STARTED_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=Customer_Stories_signup_button",
  CUSTOMER_STORIES_JOIN_REVOLUTION_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=Customer_Stories_signup_bottom_button",
  RESOURCES_EXPLORE_NOW_BTN:
    "?utm_source=direct&utm_medium=website&utm_campaign=Resources_signup_bottom_button",
  LEDGERS_GET_STARTED_BTN:
    "?utm_source=Direct&utm_medium=Website&utm_campaign=Ledgers+-+Get+Started+Button",
  LEDGERS_JOIN_REVOLUTION_BTN:
    "?utm_source=Direct&utm_medium=Website&utm_campaign=Ledgers+-+Join+The+Revolution+Button",
  DEVELOPER_DOCS_HEADER_BTN:
    "?utm_source=Decentro+Website&utm_medium=Developers+Button&utm_campaign=Website+Home+Developers",
  DEVELOPER_DOCS_FOOTER_BTN:
    "?utm_source=Decentro+Website&utm_medium=Developers+Button+Footer&utm_campaign=Website+Home+Developers+Footer",
  DEVELOPER_DOCS_KYC_ONBOARDING_BTN:
    "?utm_source=Decentro+Website&utm_medium=KYC+Page&utm_campaign=Website+KYC+Page+Explore+Docs",
  DEVELOPER_DOCS_ACCOUNTS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Accounts+Page&utm_campaign=Website+Accounts+Page+Explore+Docs",
  DEVELOPER_DOCS_SAVINGS_ACCOUNT_BTN:
    "?utm_source=Decentro+Website&utm_medium=Accounts+Section&utm_campaign=Savings+Accounts+Page+Explore+Docs",
  DEVELOPER_DOCS_VIRTUAL_ACCOUNT_BTN:
    "?utm_source=Decentro+Website&utm_medium=Accounts+Section&utm_campaign=Virtual+Accounts+Page+Explore+Docs",
  DEVELOPER_DOCS_BUSINESS_ACCOUNT_BTN:
    "?utm_source=Decentro+Website&utm_medium=Accounts+Section&utm_campaign=Business+Accounts+Page+Explore+Docs",
  DEVELOPER_DOCS_PAYMENTS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Payments+Section&utm_campaign=Payments+Page+Explore+Docs",
  DEVELOPER_DOCS_WALLET_CARDS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Cards+Section&utm_campaign=Cards+Page+Explore+Docs",
  DEVELOPER_DOCS_LEDGERS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Ledgers+Section&utm_campaign=Ledgers+Page+Explore+Docs",
  DEVELOPER_DOCS_NEOBANKS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Neobanks+Vertical&utm_campaign=Website+Neobanks+Page+Explore+Docs",
  DEVELOPER_DOCS_MARKETPLACES_BTN:
    "?utm_source=Decentro+Website&utm_medium=Marketplaces+Vertical&utm_campaign=Website+Marketplaces+Page+Explore+Docs",
  DEVELOPER_DOCS_ERPS_BTN:
    "?utm_source=Decentro+Website&utm_medium=ERPS+Vertical&utm_campaign=Website+ERPS+Page+Explore+Docs",
  DEVELOPER_DOCS_GIG_ECONOMY_BTN:
    "?utm_source=Decentro+Website&utm_medium=GigPlatforms+Vertical&utm_campaign=Website+GigPlatforms+Page+Explore+Docs",
  DEVELOPER_DOCS_PSP_BTN:
    "?utm_source=Decentro+Website&utm_medium=Payments+Vertical&utm_campaign=Website+Payments+Page+Explore+Docs",
  DEVELOPER_DOCS_WEALTH_AND_PERSONAL_FINANCE_BTN:
    "?utm_source=Decentro+Website&utm_medium=Wealth+Vertical&utm_campaign=Website+Wealth+Page+Explore+Docs",
  DEVELOPER_DOCS_NBFC_BTN:
    "?utm_source=Decentro+Website&utm_medium=NBFCs+Vertical&utm_campaign=Website+NBFCs+Page+Explore+Docs",
  DEVELOPER_DOCS_CRYPTO_BTN:
    "?utm_source=Decentro+Website&utm_medium=CryptoNFT+Vertical&utm_campaign=Website+CryptoNFT+Page+Explore+Docs",
  DEVELOPER_DOCS_CKYC_API_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Website+Resources+CKYC+API+Docs",
  DEVELOPER_DOCS_GST_API_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Website+Resources+GST+API+Docs",
  DEVELOPER_DOCS_UPI_API_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Website+Resources+UPI+API+Docs",
  DEVELOPER_DOCS_CREDIT_BUREAU_API_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Website+Resources+CreditBureau+API+Docs",
  DEVELOPER_DOCS_UPI_AUTOPAY_API_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+UPI+AutoPay+Docs+Button",
  DEVELOPER_DOCS_ENACH_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+ENACH+Docs+Button",
  CKYC_EXPLORE_NOW_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+CKYC+Explore+Now+Button",
  CKYC_TALK_TO_EXPERTS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+CKYC+Talk+to+Experts+Button",
  CKYC_SIGNUP_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+CKYC+Sign+Up+Button",
  GST_EXPLORE_NOW_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+GST+Explore+Now+Button",
  GST_TALK_TO_EXPERTS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+GST+Talk+to+Experts+Button",
  GST_SIGNUP_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+GST+Sign+Up+Button",
  UPI_EXPLORE_NOW_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+UPI+Explore+Now+Button",
  UPI_TALK_TO_EXPERTS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+UPI+Talk+to+Experts+Button",
  UPI_SIGNUP_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+UPI+Sign+Up+Button",
  CREDIT_BUREAU_EXPLORE_NOW_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+Credit+Explore+Now+Button",
  CREDIT_BUREAU_GET_STARTED_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+Credit+Sign+Up+Button",
  CREDIT_BUREAU_TALK_TO_EXPERTS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+Credit+Talk+to+Experts+Button",
  UPI_AUTOPAY_EXPLORE_NOW_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+UPI+AutoPay+Explore+Now+Button",
  UPI_AUTOPAY_TALK_TO_EXPERTS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+UPI+AutoPay+Talk+to+Experts+Button",
  UPI_AUTOPAY_GET_STARTED_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+UPI+AutoPay+Sign+Up+Button",
  ENACH_EXPLORE_NOW_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+ENACH+Explore+Now+Button",
  ENACH_TALK_TO_EXPERTS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+ENACH+Talk+to+Experts+Button",
  ENACH_GET_STARTED_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+ENACH+Sign+Up+Button",
  DIGILOCKER_LAUNCH_BANNER:
    "?utm_source=website&utm_medium=top+banner&utm_campaign=digilocker+launch",
  DIGILOCKER_EXPLORE_NOW_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+Digilocker+Explore+Now+Button",
  DIGILOCKER_TALK_TO_EXPERTS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+Digilocker+Talk+to+Experts+Button",
  DIGILOCKER_GET_STARTED_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+Digilocker+Get+Started+Button",
  DIGILOCKER_DOCS_BTN:
    "?utm_source=Decentro+Website&utm_medium=Resources+Page&utm_campaign=Resources+-+Digilocker+Docs+Button",
  TEMP_BLOGS_UTM_GENERIC:
    "?utm_source=website&utm_medium=top+banner&utm_campaign=investment+app+listicle",
};

export default utmtags;
